version: '3'

volumes:
  pgdata:
    driver: local
  dbdump:
    driver: local

services:
  db:
    build: postgres-dockerfile
    restart: unless-stopped
    env_file:
      - ./postgres-dockerfile/postgres.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "5432:5432"

  musicbrainz:
    build: musicbrainz-dockerfile
    ports:
      - "5000:5000"
    volumes:
      - dbdump:/media/dbdump
    restart: unless-stopped
    env_file:
      - ./postgres-dockerfile/postgres.env
    environment:
      - MUSICBRAINZ_USE_PROXY=1
    depends_on:
      - db